# NGINX global ayarları
user  nginx;
worker_processes  1;

# Genel hata ve erişim logları
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

# HTTP sunucusu ayarları
events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Gelişmiş log ayarları
    access_log  /var/log/nginx/access.log;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 2048;

    # HTTP üzerinden çalışan bir sunucu bloğu
    server {
        listen       80;
        server_name  localhost;

        # Root dizini ve index ayarları
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # Basit bir statik dosya sunma
        location / {
            root /usr/share/nginx/html/dist;
            index index.html;
        }

        error_page 404 /404.html;
    }
}

