secrets:
  db_password:
    file: /home/bsoykan/my_local/inception/secrets/db_password.txt
  db_root_password:
    file: /home/bsoykan/my_local/inception/secrets/db_root_password.txt
  credentials:
    file: /home/bsoykan/my_local/inception/secrets/credentials.txt

networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/bsoykan/data/wordpress

  wordpress_data:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/bsoykan/data/wordpress

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306" 
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    secrets:
      - db_password
      - db_root_password
      - credentials
#
#  nginx:
#    container_name: nginx
#    build: ./requirements/nginx
#    ports:
#      - "443:443"
#    volumes:
#      - wordpress_data:/var/www/html
#    env_file:
#      - .env
#    networks:
#        - inception-network
#    secrets:
#      - db_password
#      - db_root_password
#      - credentials
#
#
#  wordpress:
#    container_name: wordpress
#    build: ./requirements/Wordpress
#    env_file:
#      - .env
#    ports:
#      - "9000:9000"
#    volumes:
#      - wordpress_data:/var/www/html
#    networks:
#      - inception-network
#    secrets:
#      - db_password
#      - db_root_password
#      - credentials
#