services:
  nginx:
    container_name: Test-nginx-1
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "8080:80"
    depends_on:
      - Wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - fileName
    secrets:
      - db_password
      - db_root_password
      - credentials

  mariadb:
    container_name: Test-mariadb-1
    build: ./requirements/mariadb
    image: mariadb:42
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
      - credentials

  wordpress:
    container_name: Test-wordpress-1
    build: ./requirements/Wordpress
    image: wordpress:42
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
      - db_root_password
      - credentials

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  credentials:
    file: ./secrets/credentials.txt

volumes:
  mariadb_data:
  wordpress_data:
